spring:
  datasource:
    url: jdbc:mysql://localhost:3307/ms
    username: root
    password: Bapu@1995

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    
  instance:
    hostname: localhost
